### PR TITLE
Add d3 and c3 to `require()` and `define()` to improve requireJS support

### PR DESCRIPTION
**Pull request by joshbode**
Hi Nicolas,

This is a fantastic library! I've got plans to use it for data exploration presentations I run at work with non-technical people and get myself the out of Excel (I basically use Excel just for pivots nowadays). I've been playing and have built a [wrapper for `pivot.js`](/joshbode/subframe) (and `datatables.js` with plans for others) for Jupyter/IPython notebook (still a work in progress, but working well, I think).

I'm using requireJS to load the scripts (including the renderers) and I was having trouble getting c3 charts to load (c3 undefined) unless I added it to the `define` in the `c3_renderers.{coffee,js}`. It didn't seem to be necessary for d3 as it seems to export globally, but I added it to `d3_renderers.{coffee,js}`, too.

I've tried out my change on your d3 and c3 examples, and it doesn't appear to have broken anything and now it works without me having to do something hackish like `window.c3 = c3`.

Please let me know what you think.

Cheers,
Josh

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Thanks for doing this! I'll get it merged shortly, once I've had time to play with it a bit.

The Jupyter wrapper looks awesome, but I'm having trouble installing it to see how it works... Can you provide some installation instructions? I'd love to contribute :)

**Comment by joshbode** [comment]
Thanks Nicolas - any contributions will be welcome :)

I'll be doing a bit more work on it this weekend to add some instructions and perhaps some better option-handling - the actual wrapper classes are very basic right now. I plan to add more visualisations - digraph renderers, etc, but my key initial requirement was to hook up a solid pivot-table explorer.

I've only tested `subframe` with Python 2.7 and the latest version of Jupyter/Notebook, but if you clone and pull all of the submodules it may work (the pivottable submodule is pointed at my fork, right now) if you install the package dependencies and `python setup.py develop`

**Comment by nicolaskruchten** [comment]
Hehe, ok, I'll try to make it work :)

Thanks again for the contribution!

**Comment by joshbode** [comment]
Thanks for the merge - here is your c3 example, rewritten to use requirejs that works properly now (which previously failed, unable to find c3): https://gist.github.com/joshbode/fbc2f96773f55a33b8b4

**Comment by nicolaskruchten** [comment]
Hi again @joshbode,

I've just pushed this https://github.com/nicolaskruchten/pivottable/blob/master/jupyter/pivottablejs.py which is a first cut at a really simple Jupyter cell-magic to invoke this library on a Pandas data frame. Would be interested in your thoughts... It basically writes out a self-contained HTML file and then opens it up in an iframe, with a link to 'pop out' into its own window. You can also save the resulting file and re-open it later.

**Comment by joshbode** [comment]
Cool! It's a good feature that it can be saved, too.

In case you don't care about standalone exportability, IPython already includes RequireJS, jQuery and jQueryUI and you could do something like in this gist (https://gist.github.com/joshbode/fbc2f96773f55a33b8b4) to hook into the already loaded local copies (just omit the paths for jquery and jqueryui), though I don't know how it would work in an IFrame.

I wanted to be able to use everything without necessarily having internet connectivity, which is why I bundled everything into subframe and place it where Jupyter will serve it statically.

**Comment by nicolaskruchten** [comment]
I see what you're trying to do. I think I will address this use-case with a "bundle local" flag which will inline all the scripts and CSS. Also: I have to repackage this as a real python module, as `%install_ext` is deprecated in Jupyter 4.0. I'll be creating a `pivottablejs` package which will be installable via pip.

**Comment by nicolaskruchten** [comment]
And here we go: https://pypi.python.org/pypi/pivottablejs feedback and/or pull-requests welcome there :)

**Comment by jaseczka** [comment]
It looks like this commit:
https://github.com/nicolaskruchten/pivottable/commit/3929b69b97fbba37e9f3c2a3373c3ba698b868d1
removed c3 from dependencies in c3_renderers module.

**Comment by nicolaskruchten** [comment]
Sorry for the breakage, @jaseczka, and thanks for the bug report. This has been fixed in [Version 2.0.0](https://github.com/nicolaskruchten/pivottable/releases/tag/v2.0.0)

**Pull request merged**
