### PR TITLE
correct filterbox placement in dom and style filterbox according to it

### PR DESCRIPTION
**Pull request by serverfire**
With previous filterbox i had problem when i added the pivottable element inside a parent element with style of `display: relative;`
Here's the fix.

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Thanks for this pull request! I'll review it shortly :)

**Comment by ValentinH** [comment]
:+1:

**Comment by nicolaskruchten** [comment]
Your code certainly works, but I'm not able to create a test case where the original one doesn't, including a parent element with `display: relative`... Can you provide a simple Fiddle or something which shows the problem please so I can better understand this change?

**Comment by nicolaskruchten** [comment]
I made some changes in this area in response to #339 with this commit:  f6a9b091c9d273791a3e0f3dd505e07bb385d162

Not sure if that solves the problem you were having...

**Pull request closed without merging**
