### PR TITLE
enhance pivot table element to be well formed for potential use with DataTables plugin

### PR DESCRIPTION
**Pull request by astechdev**
@nicolaskruchten I was hoping to enhance the pivot table html element in order to leverage the DataTables jQuery plugin. However, since the table was missing a tbody element (http://legacy.datatables.net/usage/) the DataTables plugin was throwing an error.

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
This is a good idea in principle but the implementation is a bit strange... the`tr`s containing only `th`s (i.e. the header rows) should be in the `thead` element, no?

**Comment by astechdev** [comment]
I will send an update later this week...sorry I have been busy at work :)

**Comment by astechdev** [comment]
@nicolaskruchten I have updated the PR. The main issue with using the DataTables Plugin with your PivotTable Plugin is that you have colspan and rowspan in the tbody tag. I added a <code> datatablesEnabled: false </code> property to the default options and allow the user to override it. If the user overrides then a DataTables Plugin compatible tbody is produced. 

To test I built a little app that initializes a table with the PivotTable Plugin 
<code> $('#tableId').pivot() </code> 
and override
<code> datatablesEnabled: true </code>

Then I enhanced the table with the DataTables Plugin
<code> $('#tableId').DataTables() </code> 

The final product is a basic DataTable with sortable columns.
pitch predict pivot table

This should open the door for leveraging any available DataTables features (https://www.datatables.net/manual/api) in the PivotTable

**Comment by nicolaskruchten** [comment]
I'm OK with adding `<thead>` and `<tbody>` but I don't think I want DataTables-related code in the core, though. If you really want DataTables-compatible output, I would recommend that you either wrap or fork the TableRenderer

**Comment by astechdev** [comment]
Are you referring to the "isDataTables" flag? That flag just removes any
rowspan or colspan from the <tbody> and I didn't really know a better way
to conditionally remove those...

**Comment by nicolaskruchten** [comment]
Yes, that's what I'm referring to. I don't really like this approach, as the rowspan/colspan is the key feature of this renderer. IMO if we want a renderer that doesn't do this, we should write a new (much simpler) one, rather than adding options to this one.

**Comment by astechdev** [comment]
Understood. I may send another pull request for a new renderer then... May
take a bit better I get around to it.

**Comment by nicolaskruchten** [comment]
ok :)

**Pull request closed without merging**
