### PR TITLE
Add "useRegexForFilters" parameter

### PR DESCRIPTION
**Pull request by csphoenix1**
With this new option, we can choose between simple filters or filter with regular expression capability.
It's very usefull for me... :)

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Thanks for this PR! I will think about if it makes sense to add a new option for this functionality.

**Comment by csphoenix1** [comment]
It's a pleasure to contribute on this really good project that you have launched :)

About this functionality, can you precise about what you are thinking?
Does you plan to make by default the regex functionality?
Or put a check box in the filter area to enable the regex for each field? This could be a good idea I think :)

**Comment by nicolaskruchten** [comment]
This seems like a bit of a power-user feature to me and I'm not sure how many people would use it, so I'm leaning towards not merging this PR at this point.

 There is also another, less intrusive extension that was proposed in #556 which I am thinking about. It may make sense to accept a 'text-filter function' as a parameter and then regex or this other proposal could work instead of an API or UI parameter.

Can you give me a few examples of when a regex option adds a ton of value? Would a fuzzy search work just as well or do you actually need the full power of regex?

**Comment by nicolaskruchten** [comment]
I.e. we could replace the current version with this type of logic: https://github.com/bevacqua/fuzzysearch

**Comment by nicolaskruchten** [comment]
OK, so I've merged into master some code which will treat the "filter" string as a regex if it's prefixed by `~`, and does `>` and `<` comparisons as well, so I'll close this PR, as the desired functionality is in master now.

**Pull request closed without merging**
