### PR TITLE
Pivottable is now able to render multi Donut charts using Plotly renderer.

### PR DESCRIPTION
**Pull request by ebellumat**
Pivottable is now able to render multi Donut charts using Plotly renderer.

Related issues: #66 #256 #457 #893 #876 
People interested on this: @kevin5657 @rjst , @worstenbrood, @rajuchapagain, @tgabrielle @kumarabrol @ambarishbh 

image
image
image

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
This is very neat, thank you! Unfortunately I'm just headed out on vacation so I will likely not have time to review it for another 10 days or so but I should be able to merge it thereafter.

My main comment right now is that we need some way of identifying the donuts, some kind of title or something. Either inside the middle or above.

**Comment by ebellumat** [comment]
Thanks for your time, don't hurry to review the code, probably i will have to do some adjustments after your review. 

Anyway, i created a issue on Plotly JS repository, number #2915 asking to automatic show a annotation with a name of a pie chart, @alexcjohnson did the analysis and generated the issue #2916 "Grid-referenced components"

> You can use layout.grid to position subplots, it would be nice if you could position annotations, shapes, images, and other items like colorbars and sliders, with reference to grid cells as well. Perhaps something like:

I will make a way to display the name of the graphics, as suggested, but, with #2915 solved or #2915 solved, it would be much easier, haha.

**Comment by ebellumat** [comment]
[#2925](https://github.com/plotly/plotly.js/issues/2915) Closed in Plotly!!

**Comment by nicolaskruchten** [comment]
Ok, I’ll implement a version of pie charts in the pivot table once a Plotly
release includes this fix

**Comment by nicolaskruchten** [comment]
First of all, thanks again for the impetus here to finally get a multi-pie implementation done. That said, here are a few notes here on why I think I'll make a slightly different implementation than the one in this PR:

1. I will use the `scalegroup` feature of plotly.js pie charts such that pies are scaled with respect to each other, so that they are a clear analogy to stacked bar charts
2. As a result I will not want to use the `hole` parameter to turn them into donuts, as in that case they areas are no longer adequately comparable
3. Similarly to the way the other `plotly_renderer` renderers work, I'll disable the text on the actual pie slices: the text isn't displayed on bars in bar charts right now so it shouldn't be displayed on pie charts either.
4. I would like some slightly smarter handling of large numbers of pies: 10 pies should render in rows of 4/4/2, for example, and 20 pies should be 5/5/5/5 and so on. I'm not sure what the exact algorithm should be but I'll play with it a bit.
5. This is a minor thing, but important to me: the CoffeeScript style in this PR is quite different from the style in the rest of the file, which would likely cause maintenance problems later.

**Comment by ebellumat** [comment]
I would like to take the occasion to say thank you and confess. First of all thanks for considering the implementation of this feature in the main project, this is the first project I do a pull request. I've used this lib since 2016, =)

**Comment by Blake-Eryx** [comment]
Please consider including the ability to (optionally) make these donut charts where you can write text in the center of them.  Although they are inferior to pie charts in terms of proper data visualization, business mangers (the people most of us make our reports for) really like them and even specifically ask for them :)

Thank you! This library rocks, I use rpivottable heavily!

**Comment by nicolaskruchten** [comment]
Thanks for your input @Blake-Eryx ! Unfortunately I don't think I'll be able to do this in the built-in renderers in the short run, partly for the datavis related reasons laid out above, and also because laying out donut chart titles in the middle of the donut is not a built-in feature of plotly.js. In general this would be a tough problem to solve because the 'hole' in a donut chart is often quite small compared the amount of text a label can contain, and automatically wrapping text in SVG charts is a bit challenge.

**Comment by nicolaskruchten** [comment]
I stand corrected! Somehow I missed that even though I did check out that
PR.

I’m still on the fence about donuts for inclusion in the core pivot table.
I don’t think I’d include both pies and donuts, and I prefer pies to
donuts. I think one could coerce the former into the latter with a
Plotly.js template though, right @alexcjohnson?

**Comment by alexcjohnson** [comment]
Correct, a donut is just a pie with a `hole` as far as plotlyjs is concerned. And titles, per that PR, work either way - by default they’re above pies and inside donuts, but that too is templatable.

**Comment by nicolaskruchten** [comment]
Thanks again for the prompting with this PR! I've got #1041 in development and it will do everything this PR does except for the `hole` to make pies into donuts.

**Comment by deepsweech** [comment]
Is this going to be available for react-pivottable.js?

**Pull request closed without merging**
