### PR TITLE
Replaced the natural sort with a date aware version

### PR DESCRIPTION
**Pull request by horner**
Replaced the natural sort with a date aware version and added a date column to the sample data for testing.
screen shot 2015-01-17 at 4 10 33 am

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Thanks for this PR!

I'm not sure I follow how this date-aware sort works... Does it assume that dates are in MM/DD/YY format or something?

The sorting function is sufficiently contentious in this library that I think I will just make it a parameter that defaults to the current implementation, so that everyone can choose their own :)

**Comment by horner** [comment]
A selectable sorting algorithm sounds nice.  Maybe even over-rideable and reversable.

It first uses a regexp to find ISO8601, RFC1123, .toString(), .toUTCString(), .toLocaleDateString(), etc date formats which should work in the majority of date sorting use-cases.  It has to do this because 
Date.parse() seems to be too smart allowing for implementation specific extensions.

From: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse
> The ECMAScript specification states: If the String does not conform to the standard format the function may fall back to any implementation–specific heuristics or implementation–specific parsing algorithm. Unrecognizable strings or dates containing illegal element values in ISO formatted strings shall cause Date.parse() to return NaN.

You can take a look at an overview of the algorithm here: http://www.overset.com/2008/09/01/javascript-natural-sort-algorithm-with-unicode-support/

My cursory testing on Chrome, Safari, and IE have worked consistently with the existing sort from http://stackoverflow.com/a/4373421/112871.

**Comment by nicolaskruchten** [comment]
Wow, that's quite the implementation, thanks for bringing it to my attention. I'm having trouble understanding how it is able to use a regex to figure out what's `Date.parse()`-able but it sure seems to work, although it gets confused about M/D/Y vs D/M/Y which is irritating to some people (http://en.wikipedia.org/wiki/Date_format_by_country) ...

**Comment by horner** [comment]
Yeah, I could enhance it to respect an i18n setting in opt to prefer M/D/Y or D/M/Y.

**Comment by horner** [comment]
I am going to make a change to the pull request.  More extensive testing shows that the performance of this natural sort is *significantly* slower than the original one. The additional regex is significant.  More to come soon.

**Comment by nicolaskruchten** [comment]
Yes, I thought that might be the case...

**Comment by nicolaskruchten** [comment]
There is now a mechanism to override the natural sort either on a per-attribute basis or globally. See [documentation](https://github.com/nicolaskruchten/pivottable/wiki/Parameters) for the `sorters` parameter and the [example](http://nicolas.kruchten.com/pivottable/examples/montreal_2014.html) which shows how to sort month names without leading numbers.

**Pull request closed without merging**
