### PR TITLE
added option to configure length of attributes list that will trigger the filter buttons

### PR DESCRIPTION
**Pull request by gchamon**
It was hardcoded on code to show filter buttons on attributes when their position in the list were greater or equal to 5. Added an attribute to `opts` to give the user the ability to configure this feature.

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Thanks for this PR, sorry to have not responded earlier... Can I ask what the motivation here is? You want filters on shorter lists than 5? Or you want to hide filters on longer lists? What number are you using?

**Comment by gchamon** [comment]
Hello! Thanks for answering.
While I still need to fix conflicts, the motivation was to have the complete filter features on shorter lists. The list length defaults to the previous value, which was 5 if I'm not mistaken. The idea is to give the programmer the choice to control the list length that will trigger the filters. One might need it on shorter lists, which was my case, others might not need or want them at all. It really should be up to the user.
Thanks once again. Kind regards.

**Comment by nicolaskruchten** [comment]
Yes I understand what you're trying to do, I'm not sure why though... Why would you need filtering on lists that are shorter than 5? Why would you want to disable filtering on more items than 5? Without understanding some clear use-cases, I will not be inclined to merge this PR...

**Comment by gchamon** [comment]
In our case it was for UI consistency. Users were expecting to filter types of gases (Kyoto, non-kyoto) and so on, the same way they would filter other information, being able to use the "clear all" and "select all" commands.
My argument is to leave the use cases to the programmer's best judgement. All in all, all it's being done is expose a hard coded variable to the outside world, leaving the default as it was. It surely doesn't hurt and make the plugin that tad more customizable.

**Comment by nicolaskruchten** [comment]
Sure but you have to remember that every single configuration option has to be documented (by me) in the wiki and I have to answer questions about it in the future and keep track of it in upgrades etc. It's not zero-cost to expose internal details :)

**Comment by gchamon** [comment]
there is that too. I could offer to help, it is only fair since we use this implementation extensively

**Comment by gchamon** [comment]
on a side note, ever considered migrating to typescript?

**Comment by nicolaskruchten** [comment]
I've never seriously considered TypeScript, no. The successor to this library is https://react-pivottable.js.org/ which was already ported to ES6, and I'm not sure I want to go back to having a compilation toolchain :)

**Pull request closed without merging**
