### PR TITLE
Adding formatHeaders to rendererOptions

### PR DESCRIPTION
**Pull request by csonto**
Hi Nicolas, this change would allow customizing row and column headers (or labels?) without having to keep large chunks of HTML in the data. See the example.

It may also be used for custom sorting - use integer indices and render the labels. :-)

Thanks for an awesome library!

Martian

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Thanks for this pull request! I'll review it shortly :)

**Comment by nicolaskruchten** [comment]
Note to self: very similar to #184

**Comment by csonto** [comment]
I did not pay much attention to that ticket as it was closed. Seems
basically the same thing. May be just with a slightly different
justification.

On Wed, Mar 4, 2015 at 2:23 PM, Nicolas Kruchten <notifications@github.com>
wrote:

> Thanks for this pull request! I'll review it shortly :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicolaskruchten/pivottable/pull/308#issuecomment-77156310>
> .
>



-- 
Marian Csontos
tel: +420 722 697 405

**Comment by csonto** [comment]
Nicolas, I have slept on it and I would like to ask you to reconsider.

One should work with *normalized data* wherever possible, not with their view representations which are subject to change. These are used e.g. in aggregators and elsewhere.

I am using rather long strings in headers for example containing URLs to commit in a git repository.

To work conveniently with these I could create an object and query that for every access. But that would be called basically everywhere. IMO it should be done the other way round and should be accessed only when rendering headers.

May be I am just misusing pivotTable to display results of our test suite... ;-)

**Comment by nicolaskruchten** [comment]
Thanks for your response! I believe that most of what you are looking for is possible with the library as it stands, even if it is implemented in a different way than that which you suggested... Check out this example http://nicolas.kruchten.com/pivottable/examples/montreal_2014.html and you will see that the underlying data just has full dates (very compact, normalized), and I used the `derivedAttributes` feature to extract month and day names, and then the `sorters` to fix the sort order of those for display.

**Pull request closed without merging**
