### PR TITLE
Added hiddenFromAggregators and hiddenFromDragDrop options to pivotUI

### PR DESCRIPTION
**Pull request by langusta**
Hi,
I have added the additional options that we've discussed in #403 . I was unsure what to include in the pull request so I included everything:
- pivot.coffee
- other repository files that have changed after compilation with `coffee -o dist -c *coffee`
- my example (random_hiddenAttributes.html) plus csv file with random data that I have created to test my changes

Please discard the examples and any unnecessary changes as you see fit. You can do that, right? This is my first pull request :) If not, then I could change the request to only include the pivot.coffee file.

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Thank you for this pull request! I've been rather busy and I have a bunch of stuff queued up for review on this project so I haven't had the chance to integrate it yet, but I promise I will get to it :)

**Comment by langusta** [comment]
No problem. That will be awesome! Thanks :)

**Comment by sluc23** [comment]
I've seen this PR haven't been merged due to conflicts, it's a pity these new (and very useful) attributes cannot be included when they are almost there. The issue is paused since 2015, so I'm not sure what was wrong with this...

Anything we can do to resume this work?

**Comment by nicolaskruchten** [comment]
@sluc23 yeah, I've done a bad job with this PR... I've been hesitating to merge it because it's a feature that isn't requested all that often and I hesitate to keep adding options to this API...

**Comment by sluc23** [comment]
Well in my experience this feature is very useful. Usually in the array's value I have mixed "dimensions" and "measures", and each has its own purpose. Ones for aggregators, the others for rows/cols, so for making the UI easier and clearer I would like to show/hide the values where they belong to

If you think this feature can still be included, I can resume the work done an create new PR. If not I'll fork it add them to my own API

cheers!

**Comment by nicolaskruchten** [comment]
I'm still pondering this change, please bear with me :)

**Comment by hannahcomeau** [comment]
I would find this feature very helpful as well :)

(fingers crossed)

**Comment by nicolaskruchten** [comment]
OK, I've just committed 824db49 which includes the changes from this PR.

Apologies again for taking so obscenely long to finalize this! I kept on thinking there was some fancier way to deal with this need (e.g. #191) but in the end this is simple and works well for many cases.

**Pull request closed without merging**
