### PR TITLE
handle missing json keys

### PR DESCRIPTION
**Pull request by nicolaskruchten**
This PR should address an issue which a number of people have raised wherein the `pivotUI()` function errors out when some records in the dataset have fields that the first record doesn't. The implementation of this fix also removes a pass on the data when the UI is first loaded, so it should load more quickly.

### CODE REVIEW

**Comment by gargulamen** [comment]
Not sure if I'm doing this wrong or not, but is the pivot.js updated? Still getting the error.

**Comment by nicolaskruchten** [comment]
@gargulamen yes, `dist/pivot.js` was updated in this PR. Are you grabbing the right version of the file? This hasn't hit the `master` branch or been released as an NPM package or anything yet...

**Comment by gargulamen** [comment]
Sorry, was getting it from npm. I don't get the error now, thanks 👍. But is it possible to hide the nulls from the rendering at all? Don't see the point to show a value for a row/col that as a null on it or a list with a "null(0)". Thanks again

**Comment by nicolaskruchten** [comment]
Well we have to show all the values for all attributes, including the null ones, otherwise filtering will not work, but if you're seeing "null (0)" that's a bug that I need to work out :)

**Comment by nicolaskruchten** [comment]
I fxed the "null (0)" issue, and I'm seeing the problem with filtering nulls now. I'll fix that and push again in a bit. Thanks for the feedback on this :)

**Comment by nicolaskruchten** [comment]
OK, null-filtering is fixed. @gargulamen can you let me know what you think?

**Comment by gargulamen** [comment]
Thanks for the fix 👍

**Comment by dcvidigal** [comment]
Hi, First of all congrats for the awesome component 😄 

I saw some issues about the null keys on json and so on, and I saw that this fix works great, but I have a question.

Does this fix clean up the null rows/colls? Or should i ask, will the null rows/cols not appear on the pivot table?

Thanks in advance 😄

**Comment by dcvidigal** [comment]
Well I thought about the 'exclusions' parameter but i was trying to avoid it.
Guess I give it a shot 😄 

Thank you very much

**Pull request merged**
