### PR TITLE
Updated locales pt, zh and es to support all default agregators.

### PR DESCRIPTION
**Pull request by ebellumat**
Some languages do not have some of the aggregators available in the English version.

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Thanks! Just curious... do you speak all three of these languages? :)

**Comment by ebellumat** [comment]
Portuguese yes, Spanish a little, Chinese I asked for help haha.

**Comment by ebellumat** [comment]
I live in Brazil, if I knew a little French I would try to move to Canada.

**Comment by nicolaskruchten** [comment]
Thanks!

**Comment by andregv** [comment]
Just a tip: when using highchart integration is missing the {and: ""} translation (all locales).

**Pull request merged**
